version: '3.3'
networks:
  lnmp-net:
    driver: bridge
services:
  openresty:
    container_name: openresty
    image: openresty/openresty
    privileged: true
    ports:
    - "8888:80"
    volumes:
    - /c/dev/www/docker/webcdn-test/nginx-conf-dir/nginx.conf:/etc/nginx/nginx.conf
    - /c/dev/www/docker/webcdn-test/nginx-conf-dir/conf.d:/etc/nginx/conf.d
    - /c/dev/www/docker/webcdn-test/nginx-conf-dir/lua:/lua
    - /c/dev/www/docker/webcdn-test/nginx-conf-dir/logs:/var/log/nginx
    - /c/dev/www/docker/webcdn-test/nginx-conf-dir/html:/www
#    depends_on:
#    - php
    restart: always
    networks:
    - lnmp-net
  php:
    container_name: php
    image: php:7.4-fpm
    privileged: true
    volumes:
    - /c/dev/www/docker/webcdn-test/php-conf-dir/logs:/usr/local/var/log
    - /c/dev/www/docker/webcdn-test/php-conf-dir/php.ini:/usr/local/etc/php/php.ini
    - /c/dev/www/docker/webcdn-test/php-conf-dir/www.conf:/usr/local/etc/php-fpm.d/www.conf
    - /c/dev/www/docker/webcdn-test/nginx-conf-dir/html:/www
    restart: always
    networks:
    - lnmp-net
